[project]
name = "pdf-to-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk==1.1.1",
    "pdf2image==1.17.0",
    "requests==2.31.0",
]
