from google.adk.agents import LlmAgent, LoopAgent, SequentialAgent
from google.adk.tools import ToolContext, agent_tool
from pydantic import BaseModel, Field

from config import GEMINI_2_FLASH

# Code Reviewer Agent
# Takes the code generated by the previous agent (read from state) and provides feedback.
entity_extractor_agent = LlmAgent(
    name="CodeReviewerAgent",
    model=GEMINI_2_FLASH,
    # Change 3: Improved instruction, correctly using state key injection
    instruction="""
    Tu es xx. A partir des evenements, identifie les entites presentes
    {extracted_events}



**Output:**
Provide your feedback as a concise, bulleted list. Focus on the most important points for improvement.
If the code is excellent and requires no changes, simply state: "No major issues found."
Output *only* the review comments or the "No major issues" statement.
""",
    description="Extrait les entitiees presente en utilisant le tool x",
    output_key="extracted_entities",
)
